---
name: "kubetail-action"
description: "Lets you tail kubernetes logs"
inputs:
  debug:
    description: "Adds action debug messages. Might contain sensitive data."
    required: false
  config:
    description: "Kubeconfig yaml contents."
    required: true
  context:
    description: "Context to use if there are multiple."
    required: false
  namespace:
    description: "Namespace to deploy to. You can use env vars here."
    required: false
  resource:
    description: "Resource to watch."
    required: false
    default: "deployment"
  name:
    description: "Name of the deployment to watch. Incompatible with selector."
    required: false
  selector:
    description: "kubectl selector for the deployments to watch. Incompatible with name."
    required: false
  timeout:
    description: "How long to try tailing for."
    required: false
    default: 300s
runs:
  using: "docker"
  image: "Dockerfile"
