---
name: "kubetail-action"
description: "Lets you tail kubernetes logs"
inputs:
  # Inputs from kubectl-action-base
  debug:
    description: "Adds action debug messages. Might contain sensitive data."
    required: false
  config:
    description: "Kubeconfig yaml contents. Can be base64 encoded or just yaml."
    required: false
  eks_cluster:
    description: "Name of the EKS cluster to interact with. Will use aws eks update-kubeconfig."
    required: false
  eks_role_arn:
    description: "The AWS IAM role to use when authenticating with EKS."
    required: false
  context:
    description: "Context to use if there are multiple."
    required: false
  namespace:
    description: "Namespace to use."
    required: false
  # kube-rollout-action specific inputs
  resource:
    description: "Resource to watch."
    required: false
    default: "deployment"
  name:
    description: "Name of the deployment to watch. Incompatible with selector."
    required: false
  selector:
    description: "kubectl selector for the deployments to watch. Incompatible with name."
    required: false
  timeout:
    description: "How long to try tailing for."
    required: false
    default: 300s
runs:
  using: "docker"
  image: "Dockerfile"
